[package]
name = "roadrunner"
version = "2.1.0"
authors = ["Juan Ibiapina <juanibiapina@gmail.com>"]

[dependencies]
hostname = "*"
users = "*"
termion = "*"
maplit = "*"
clap = "*"

[dependencies.nom]
version = "^4.0"
features = ["regexp", "verbose-errors"]
