[package]
name = "roadrunner"
version = "0.1.0"
authors = ["Juan Ibiapina <juanibiapina@gmail.com>"]

[dependencies]
hostname = "*"
users = "*"

[dependencies.nom]
version = "^4.0"
features = ["regexp", "verbose-errors"]
