name: Rust

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install rust stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - name: Install cross
      run: cargo install cross
    - name: Create Linux Artifact
      run: |
        cross build --target x86_64-unknown-linux-gnu --release
        mkdir dist
        cp target/x86_64-unknown-linux-gnu/release/roadrunner dist/
        cd dist
        tar czf roadrunner-${GITHUB_REF#refs/tags/}-x86_64-unknown-linux-gnu.tar.gz *
        cd ..
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
        bin/hub release create -a "dist/roadrunner-${GITHUB_REF#refs/tags/}-x86_64-unknown-linux-gnu.tar.gz" -m ${GITHUB_REF#refs/tags/} ${GITHUB_REF#refs/tags/}
