name: Rust

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install rust stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - name: Install cross
      run: cargo install cross
    - name: Create Linux release
      run: |
        cross build --target x86_64-unknown-linux-gnu --release
        mkdir dist
        cp target/x86_64-unknown-linux-gnu/release/roadrunner dist/
        cd dist
        tar czf roadrunner-${GITHUB_REF#refs/tags/}-x86_64-unknown-linux-gnu.tar.gz *
    - name: Upload Linux release
      uses: Xotl/cool-github-releases@v1
      with:
        mode: update
        tag_name: ${GITHUB_REF#refs/tags/}
        body_mrkdwn: ""
        assets: dist/roadrunner-${GITHUB_REF#refs/tags/}-x86_64-unknown-linux-gnu.tar.gz
        github_token: ${{ secrets.GITHUB_TOKEN }}
