name: Rust

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install rust stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - name: Install cross
      run: cargo install cross
    - name: Create Linux release
      run: |
        cross build --target x86_64-unknown-linux-gnu --release
        mkdir dist
        cp target/x86_64-unknown-linux-gnu/release/roadrunner dist/
        cd dist
        tar czf ../roadrunner-${GITHUB_REF#refs/tags/}-x86_64-unknown-linux-gnu.tar.gz *
        ls
