name: Rust

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install rust stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Install bats
      run: git clone --depth 1 https://github.com/sstephenson/bats.git
    - name: Configure git
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Example"
    - name: Run tests
      run: PATH="./bats/bin:$PATH" make
